Update yt-watch script

diff --git a/bin/yt-watch b/bin/yt-watch
--- a/bin/yt-watch
+++ b/bin/yt-watch
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
-api_key="AIzaSyAr8NhkzkZlzo383lvPVP2ik6KFGnZ98Jw"
-
 c_red="\033[1;31m"
 c_green="\033[1;32m"
 c_blue="\033[1;34m"
 c_reset="\033[0m"
 tmp_file="/tmp/yt-hist"
+search_file="/tmp/yt-script-search"
+rm -rf "$search_file"
 
 
 formatPrint(){
@@ -28,7 +28,7 @@ notify() {
   local title="$2"
   
   notify-send -u normal \
-              -t 5000 "$action: $title"
+              -t 5000 "$action:" "$title"
 }
 
 playVideo() {
@@ -37,25 +37,34 @@ playVideo() {
 }
 
 searchQuery() {
-  if ! command -v jq &> /dev/null; then
-    die "jq is not installed\n"
-  fi
-
   tput reset
-
-  printf "${c_red}Search YouTube Video:${c_reset} "
+  printf "${c_red}Search YouTube:${c_reset} "
   read -r query
-
+  
   if [[ "$query" == "" ]]; then
-    die "No query term specified\n"
+    die "No query term specified.\n"
   fi
-
-  query=$(printf "%s" "$query" | tr ' ' '+')
+  
+  query="${query// /+}"
   tput reset
 
-  urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${api_key}"
-  curl -s "${urlstring}" | jq -r '.items[] | "\(.snippet.channelTitle) --> \(.snippet.title) https://youtu.be/\(.id.videoId)"' > "$tmp_file"
+  if ! command -v yt-dlp &> /dev/null; then
+    die "yt-dlp is not installed\n"
+  fi
 
+  if ! command -v mpv &> /dev/null; then
+    die "mpv is not installed\n"
+  fi
+
+  if [ -n "$1" ]; then
+    search_length="$1"
+  else
+    search_length="5"
+  fi
+
+  printf "${c_red}Searching with yt-dlp.${c_reset} "
+  yt-dlp --verbose -j "ytsearch$search_length:$query" > $tmp_file
+  
   searchVideo
 }
 
@@ -68,19 +77,30 @@ searchHistory() {
 }
 
 searchVideo() {
-  formatPrint "$tmp_file"
+  tput reset
+
+  printf "${c_red}Formatting output.${c_reset} "
+  while IFS="" read -r line;do
+	  uploader=$( echo $line | sed 's/.*"uploader": "\(.*\)", "uploader_id.*/\1/g')
+	  title=$( echo $line | sed 's/.*"fulltitle": "\(.*\)", "epoch.*/\1/g')
+	  url=$( echo $line | sed 's/.*"webpage_url": "\(.*\)", "categories.*/\1/g')
+	  echo "${uploader} --> ${title} ${url}" >> $search_file
+  done < $tmp_file
+
+  tput reset
+  formatPrint "$search_file"
 
   printf "\n${c_red}Enter Choice:${c_reset} "
-    read -r choice
-    [ "$choice" -eq "$choice" ] 2>/dev/null || die "${c_red}Invalid Number Entered.${c_reset}\n"
-    [[ $(wc -l ${tmp_file} | cut -d' ' -f1) -lt $choice  ]] || [[ $choice -lt 0 ]] || [[ $choice -eq 0 ]] && die "${c_red}Invalid choice range.${c_reset}\n"
-    
-    video=$(awk -v choice="$choice" '{if(NR==choice) print $0}' ${tmp_file})
-    videourl=$(printf "%s" "$video" | awk '{ print $NF }')
-    videotitle=$(printf "%s" "$video" | sed 's/^[^-]*--> //g' | sed 's/ http.*//g')
+  read -r choice
+  [ "$choice" -eq "$choice" ] 2>/dev/null || die "${c_red}Invalid Number Entered.${c_reset}\n"
+  [[ $(wc -l ${search_file} | awk '{print $1}') -lt $choice  ]] || [[ $choice -lt 0 ]] || [[ $choice -eq 0 ]] && die "${c_red}Invalid choice range.${c_reset}\n"
+  
+  video=$(awk -v choice="$choice" '{if(NR==choice) print $0}' "$search_file")
+  videourl=$(echo "$video"|awk '{print $NF}')  
+  format_title=$(echo "$video"|sed 's/^.*--> \(.*\) https:\/\/.*/\1/')
 
-    notify "Playing Video" "$videotitle" && playVideo "$videourl"
-    tput reset
+  notify "Playing Youtube Video" "$format_title" && playVideo "$videourl"
+  tput reset
 }
 
 downloadVideo() {
@@ -105,6 +125,15 @@ downloadMp3() {
   yt-dlp --extract-audio --audio-format=mp3 --audio-quality=0 "$id"
 }
 
+_sigterm(){
+  tput reset
+  die 
+}
+
+trap _sigterm SIGTERM
+trap _sigterm SIGINT
+
+
 # Play youtube video link from clipboard
 if [[ "$1" == "" ]]; then
   notify "Playing Video" "$(xclip -o)" && playVideo "$(xclip -o)"
@@ -124,6 +153,11 @@ elif [[ "$1" == "-dm" || "$1" == "--download-mp3" ]]; then
 # Search youtube videos
 elif [[ "$1" == "-s" || "$1" == "--search" ]]; then
   searchQuery
+
+# Search youtube videos with specifying the result length.
+# The larger the value, the longer it takes.
+elif [[ "$1" == "-sl" || "$1" == "--search-length" ]]; then
+  searchQuery "$2"
 
 # Uses recent results from recent search query. 
 elif [[ "$1" == "-h" || "$1" == "--history" ]]; then
